// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xosfjdycemjtghpjcvzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvc2ZqZHljZW1qdGdocGpjdnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNDUzNzAsImV4cCI6MjA2MjgyMTM3MH0.jmDD_EwfGFDZpyp0qqxfRF5KArhdi95wGIJKVaRZFtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);